name: jw_video_player
description: A flutter plugin for the JWPlayer platform.
version: 0.0.1
homepage: 
repository: https://github.com/DavidPerezP124/jwplayer_plugin/tree/main

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js: ^0.6.5 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: jwplayer.jwplayer
        pluginClass: JwplayerPlugin
      ios:
        pluginClass: JwplayerPlugin
      web:
        pluginClass: JWPlayerWeb
        fileName: web/jwplayer_web.dart