name: jwplayer
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0-102.0.dev <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  js:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: jwplayer.jwplayer
        pluginClass: JwplayerPlugin
      ios:
        pluginClass: JwplayerPlugin
      web:
        pluginClass: JWPlayerWeb
        fileName: web/jwplayer_web.dart