name: Test example app build
on:
  pull_request:
    branch:
      - main
jobs:
  build_ios:
    working-directory: jwplayer/example
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign
  build_android:
    runs-on: ubuntu-latest
    steps:
    working-directory: jwplayer/example
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.0.5'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
  build_web:
    working-directory: jwplayer/example
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web